### ISSUE TITLE
Avancerade inställningar funkar inte riktigt

### ISSUE THREAD

**Issue by bobinush** [1dv611-meridium/1dv611-meridium#15]
Jag testade med standardinställningarna och sen kopierade det kommandot till avancerade och tog bort output flaggan -O. `www.vecka.nu -s0 -N0 -A100000000000 -%c10 -C0 -f2 -q`

Det blir `.../httrack.exe" undefined -O C:\Users\Robin\OneDrive\Skola\1DV611 Mjukvaruutvecklingsprojekt i grupp\1dv611-meridium\archives/hostname_2018-04-23_17-57-49-52`

Alltså mina inställningar blir undefined.

Felet: Ni har ändrat namn i HTML-formen från rawDataInput till advancedSetting men glömt ändra i backend.
Samma gäller när jag sparar en avancerad arkivering så syns inte mitt kommando när jag sen går till `schedules/edit/` i webbläsaren, antar att man glömt uppdatera där också.

Innan ni ändrar namn på saker och ting, sök igenom projektet om det används någon annanstans.

**Comment by sios13** [comment]
Detta ska nu vara fixat!
