### ISSUE TITLE
httrackWrapper callback error

### ISSUE THREAD

**Issue by bobinush** [1dv611-meridium/1dv611-meridium#16]
När det blir fel i httrackWrapper så gör den en callback med bara ett felmeddelande, inte båda variablarna (error, response). Därför kan man inte läsa reponse.email eller response.url (archivesController.js rad 53 och 56).

- [x] returnera en response från httrackWrapper vid error också så ni sen kan läsa epost och url.

**Comment by sios13** [comment]
httrackWrapper skickar nu tillbaka url och email vid error.
