### ISSUE TITLE
Inget felmeddelande när man försöker återställa ett lösenord till en e-mail som inte finns

### ISSUE THREAD

**Issue by AlexNaga** [1dv611-meridium/1dv611-meridium#17]
Klienten får inget svar tillbaka. Den bara står och tuggar.

Bäst vore om vi skickade tillbaka ett svar oavsett om e-posten finns eller inte. Något i stil med: _"Om den angivna e-postadressen finns i vårt system så har vi nu skickat en återställningslänk till den."_

**Comment by bobinush** [comment]
Superbra ide! Det kan faktiskt klassas som en säkerhetsrisk att visa ett felmeddelande om man tex informerar om att en e-post är registrerad eller inte, därför är det bra att visa samma meddelande oavsett utfall. 

Men om den inte finns registrerad hos oss så kan man vara schysst och skicka ett mail där det står "någon har försökt återställa ett lösenord till den här e-posten men vi har den inte registrerad hos oss."

**Comment by AlexNaga** [comment]
Ja absolut det skulle vara schysst!

Dock ser jag framför mig ett möjligt scenario att någon skulle spamma återställningsformen med en massa random e-postadresser och helt plötsligt har det gjort vår tjänst till en spam-tjänst.

**Comment by rjosih** [comment]
Fixat.
