### ISSUE TITLE
Spara avancerade inställningar

### ISSUE THREAD

**Issue by bobinush** [1dv611-meridium/1dv611-meridium#18]
Kommandot man skriver in i avancerade inställningar sparas inte i databasen.
När jag försöker uppdatera en sparad avancerad inställning får jag 404

- [x] Spara kommandot från avancerade inställningar i databasen
- [x] Fixa 404 vid uppdatering av sparad avancerad inställning

**Comment by sios13** [comment]
Detta ska nu vara fixat!

**Comment by bobinush** [comment]
När jag klickar in på min sparade schemaläggning får jag endast "https://vecka.nu" i kommandofältet.
Hela strängen är dock sparad i databasen: "https://vecka.nu -O -s0 -N0 -A100000000000 -%c10 -C0 -f2 -q"

Samma gäller efter att jag har uppdaterat den.

**Comment by sios13** [comment]
Fick det nu äntligen att funka!

Det var fel på front-end. Istället för `value={{ schedule.advancedSetting }}` skulle det stå `value="{{ schedule.advancedSetting }}"`
