### ISSUE TITLE
Navigeringsmenyn i mobil

### ISSUE THREAD

**Issue by fridamelin** [1dv611-meridium/1dv611-meridium#19]
Knapparna ska ha samma längd, ta upp hela bredden.
Texten skall vara i mitten vertikalt.
fixa hem-knappen också

**Comment by bobinush** [comment]
Ska fungera efter [denna](https://github.com/1dv611-meridium/1dv611-meridium/commit/413fc0a698dd8f53aa81bba347be5bc41d549ccd) commit. Märker dock att det bara fungerar i webbläsaren men i mobilen kan man inte trycka på hamburgermenyn..

**Comment by fridamelin** [comment]
Mobilanpassa inställningar (archive)

**Comment by sios13** [comment]
Navigeringsmenyn fungerar fint i min telefon.
