### ISSUE TITLE
FRONT END - Schemaläggningar

### ISSUE THREAD

**Issue by fridamelin** [1dv611-meridium/1dv611-meridium#25]
Tabellen ska innehålla (från vänster):

- [x] URL (behövs småfix för att få det att fungera med avancerade inställningar)
- [x] Sub-url
- [x] Exkludera
- [x] Schemaläggning
- [x] Senast uppdaterad

Alla värden i tabellen ska vara användarvänliga!

- [x] Pagination

![31016667_10213342019883523_1110960768_o](https://user-images.githubusercontent.com/21335658/39244853-43f193b8-4892-11e8-8e4e-b1f5dae9688a.jpg)

**Comment by fridamelin** [comment]
Ändra "Senast uppdaterad : 2 days ago" 
Allt ska vara på svenska så det borde vara ex. 2 dagar sedan. :)

**Comment by bobinush** [comment]
[Fixat](https://github.com/1dv611-meridium/1dv611-meridium/commit/bebc847435c4a88a5d38c04045c9b1fb2e4ea06f)
