### ISSUE TITLE
BACKEND - Enskild schemaläggning

### ISSUE THREAD

**Issue by fridamelin** [1dv611-meridium/1dv611-meridium#36]
- [x] Fixa navigeringsmenyn på enskild schemaläggning. 
- [x] Flashmeddelande när schemaläggningen tagits bort
- [x] Redirecta till "Lista schemaläggningar" när en enskild tagits bort
- [x] När man har Pausat och vill starta igen fungerar inte Start-knappen
- [x] Radera fungerar ej
- [x] Arkivera nu fungerar ej

**Comment by sios13** [comment]
La till validering av inställningar när man trycker på 'Arkivera nu'.
