### ISSUE TITLE
Förhandsgranska arkiv

### ISSUE THREAD

**Issue by fridamelin** [1dv611-meridium/1dv611-meridium#49]
Öppna i en iframe istället för ny tabb

**Comment by AlexNaga** [comment]
Knappen för att öppna i en iframe är skapad men är bortkommenterad i listArchives.hbs.

**Comment by bobinush** [comment]
Jag tog mig friheten och körde på en ny flik istället för en iframe. Blev en enklare lösning än i en iframe och funkar rätt bra nu.
