### ISSUE TITLE
Startsida ej inloggad information

### ISSUE THREAD

**Issue by bobinush** [1dv611-meridium/1dv611-meridium#60]
"Följer alla krav från Riksarkivet och ISO-standarder för arkivering"

Gör vi verkligen det eller är detta något vi bara skrivit?

**Comment by fridamelin** [comment]
Jag kollade vad det innebar och jag tror vi uppfyller det men vi kan kolla igenom det allihopa. 

Alla de 3 punkterna är lite oklara, så vi kan ju ändra dem ihop :D
