### ISSUE TITLE
Förslag

### ISSUE THREAD

**Issue by bobinush** [1dv611-meridium/1dv611-meridium#66]
Knapparna _Arkivera_ och _Spara_ ger lite oväntat resultat tillsammans med inställningen _Schemaläggning_. Vilket ger utrymme till eventuella fel och missförstånd.

**Scenario 1:** Ingen schemaläggning, tryck _Spara_.
**Ev. förväntat resultat:** Arkiveringen sparas, men var?

**Scenario 2:** Välj en schemaläggning, tryck _Arkivera_.
**Ev. förväntat resultat:** En arkivering skall startas direkt och samtidigt schemaläggas. (alltså sparas undan)

**Förslag**
1. Ta bort båda knappen _Arkivera_.
2. _Spara_ sparar varje "inställning".
3. Ta bort menyn _Mina arkiveringar_, eftersom varje arkivering kommer då kopplas till en "inställning".
4. Byt namn på menyn _Mina schemaläggningar_ till _Mina arkiveringar_. 
5. _Mina arkiveringar_ kommer då fungera som en slags historik.

**Diskussion:** Ska knappen köra igång en arkivering direkt eller inte? 
Ska _Mina arkiveringar_ fungera som en historik eller ska "inställningar" som inte är schemalagda separeras från de som är schemalagda?

**Comment by fridamelin** [comment]
Jag är med på att Mina arkiveringar ska fungera som historik och jag tycker att när man sparar en inställning så ska den arkiveras också. 
Men frågan är då om man ens behöver ha "spara"-knappen, det kanske endast behövs en "Arkivera" (om den nu ska innehålla bägge funktionerna) ..

**Comment by sios13** [comment]
Gjorde nu en commit med dessa förslag. Knappen heter 'Arkivera och spara' men det går såklart enkelt att ändra.

Angående menyn Mina arkiveringar, tycker ni den ska ha url '/schedules' eller '/archives'?

**Comment by bobinush** [comment]
Kör på archives. Jag tycker att vi ska ta bort begreppet schemaläggning helt och hållet för en användare (förutom inställningen).
