### ISSUE TITLE
Namngivning zip-fil

### ISSUE THREAD

**Issue by bobinush** [1dv611-meridium/1dv611-meridium#79]
Namnet på filen får fel nummer på månaden. En arkivering gjord i maj får nummer 4. (Antagligen är månaderna upplagd som 0 baserat index)

**Comment by fridamelin** [comment]
Behöver vi verkligen åtgärda detta?

**Comment by bobinush** [comment]
Rätt ska vara rätt! bara skriva in +1 någonstans i koden.
