### ISSUE TITLE
Flash-meddelande dyker inte upp vid radering av schemaläggning

### ISSUE THREAD

**Issue by AlexNaga** [1dv611-meridium/1dv611-meridium#86]
När man tar bort en schemaläggning och skickas tillbaka till _/archives_ så dyker inte flash-meddelande upp.

Rad 58 i modal-scripts.js påstår att:
"This will also show the flash message upon reload"

Detta funkar inte

**Comment by fridamelin** [comment]
Vi bestämde att vi inte skulle göra detta

**Comment by bobinush** [comment]
Det var pga backend. Om man la meddelandet i req.session.flash så funkade det, men då syntes meddelandet också om det blev något fel och man gick till nästa sida..
Så man fick välja vilken bugg det skulle vara, finns säkert en lösning som fixar båda!
