### ISSUE TITLE
Texten i modal-fönstret för radering uppdaters inte

### ISSUE THREAD

**Issue by AlexNaga** [1dv611-meridium/1dv611-meridium#90]
Vid radering av ett arkiv / inställning och växlar mellan dessa raderingsknappar, så behöver man klicka två gånger på Radera, för att texten ska uppdateras.

![delete-buttons](https://i.imgur.com/TUK9MQW.png)
![modal-box](https://i.imgur.com/znnpImv.png)

**Comment by bobinush** [comment]
Fixat! https://github.com/1dv611-meridium/1dv611-meridium/commit/b48a9a0ad3ec1ac3c1d19fa2803d634367dc4088
